name: FloatyPlugin
description: The core, monolithic plugin for The Floating City.
authors: [ TehBrian ]
website: https://github.com/thefloatingcity/FloatyPlugin

version: ${version}
main: xyz.tehbrian.floatyplugin.FloatyPlugin
api-version: 1.18

depend: [ LuckPerms ]
load: STARTUP
