name: FloatyPlugin
description: ${description}
authors: [ TehBrian ]
website: https://github.com/thefloatingcity/FloatyPlugin

version: ${version}
main: xyz.tehbrian.floatyplugin.FloatyPlugin
api-version: 1.19

depend: [ LuckPerms ]
load: STARTUP
