name: Helios
description: ${description}
authors: [ TehBrian ]
website: https://github.com/thefloatingcity/Helios

version: ${version}
main: city.thefloating.helios.Helios
api-version: 1.20

depend: [ LuckPerms ]
load: STARTUP
