name: FloatyPlugin
description: The core, monolithic plugin for The Floating City.
authors: [ TehBrian ]
website: https://github.com/thefloatingcity/FloatyPlugin

version: ${version}
main: xyz.tehbrian.floatyplugin.FloatyPlugin
api-version: 1.17

permissions:
  floatyplugin.chatcolor:
    description: Permission to color chat text.
    default: op
  floatyplugin.build:
    description: Permission to interact with the world.
    default: op
