name: FloatyPlugin
description: ${description}
authors: [ TehBrian ]
website: https://github.com/thefloatingcity/FloatyPlugin

version: ${version}
main: city.thefloating.floatyplugin.FloatyPlugin
api-version: 1.20

depend: [ LuckPerms ]
load: STARTUP
