name: TFCPlugin
description: The core, monolithic plugin for The Floating City.
authors: [ TehBrian ]
website: https://github.com/thefloatingcity/TFCPlugin

version: ${version}
main: xyz.tehbrian.tfcplugin.TFCPlugin
api-version: 1.16

permissions:
  tfcplugin.chatcolor:
    description: Permission to color chat text.
    default: op
  tfcplugin.build:
    description: Permission to interact with the world.
    default: op
